/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.amlehstation.massenger;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;

/**
 *
 * @author ASD
 */
public class ADDD_SCREEN extends javax.swing.JFrame {

    /**
     * Creates new form ADDD_SCREEN
     */
    public ADDD_SCREEN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JPhone = new javax.swing.JTextField();
        JName = new javax.swing.JTextField();
        JEmail = new javax.swing.JTextField();
        jSaturday = new javax.swing.JRadioButton();
        jSunday = new javax.swing.JRadioButton();
        jMonday = new javax.swing.JRadioButton();
        jTuesday = new javax.swing.JRadioButton();
        jWednesday = new javax.swing.JRadioButton();
        jThursday = new javax.swing.JRadioButton();
        jFriday = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        SaturdayComboBoxFH = new javax.swing.JComboBox<>();
        SaturdayComboBoxFM = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        SaturdayComboBoxTH = new javax.swing.JComboBox<>();
        SaturdayComboBoxTM = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        SundayComboBoxFH = new javax.swing.JComboBox<>();
        SundayComboBoxFM = new javax.swing.JComboBox<>();
        SundayComboBoxTH = new javax.swing.JComboBox<>();
        SundayComboBoxTM = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        MondayComboBoxFH = new javax.swing.JComboBox<>();
        MondayComboBoxFM = new javax.swing.JComboBox<>();
        MondayComboBoxTH = new javax.swing.JComboBox<>();
        MondayComboBoxTM = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TuesdayComboBoxFH = new javax.swing.JComboBox<>();
        TuesdayComboBoxFM = new javax.swing.JComboBox<>();
        TuesdayComboBoxTH = new javax.swing.JComboBox<>();
        TuesdayComboBoxTM = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        WednesdayComboBoxFH = new javax.swing.JComboBox<>();
        WednesdayComboBoxFM = new javax.swing.JComboBox<>();
        WednesdayComboBoxTH = new javax.swing.JComboBox<>();
        WednesdayComboBoxTM = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ThursdayComboBoxFH = new javax.swing.JComboBox<>();
        ThursdayComboBoxFM = new javax.swing.JComboBox<>();
        ThursdayComboBoxTH = new javax.swing.JComboBox<>();
        ThursdayComboBoxTM = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        FridayComboBoxFH = new javax.swing.JComboBox<>();
        FridayComboBoxFM = new javax.swing.JComboBox<>();
        FridayComboBoxTH = new javax.swing.JComboBox<>();
        FridayComboBoxTM = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51), 2));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 3, 36)); // NOI18N
        jLabel1.setText("Add doctor ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51), 2));
        jPanel3.setForeground(new java.awt.Color(51, 0, 51));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel2.setText("Name : ");

        jLabel3.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel3.setText("time : ");

        jLabel4.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel4.setText("Email : ");

        jLabel5.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel5.setText("Phone : ");

        JPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPhoneActionPerformed(evt);
            }
        });

        JName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNameActionPerformed(evt);
            }
        });

        JEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEmailActionPerformed(evt);
            }
        });

        jSaturday.setText("Saturday");
        jSaturday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaturdayActionPerformed(evt);
            }
        });

        jSunday.setText("Sunday");
        jSunday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSundayActionPerformed(evt);
            }
        });

        jMonday.setText("Monday");
        jMonday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMondayActionPerformed(evt);
            }
        });

        jTuesday.setText("Tuesday");
        jTuesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTuesdayActionPerformed(evt);
            }
        });

        jWednesday.setText("Wednesday");

        jThursday.setText("Thursday");

        jFriday.setText("Friday");

        jLabel6.setText("FROM");

        SaturdayComboBoxFH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01 PM", "02 PM", "03 PM", "04 PM", "05 PM", "06 PM", "07 PM", "08 PM", "09 PM", "10 PM", "11 PM", "12 AM", "01 AM", "02 AM", "03 AM", "04 AM", "05 AM", "06 AM", "07 AM", "08 AM", "09 AM", "10 AM", "11 AM", "12 PM" }));
        SaturdayComboBoxFH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaturdayComboBoxFHActionPerformed(evt);
            }
        });

        SaturdayComboBoxFM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        SaturdayComboBoxFM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaturdayComboBoxFMActionPerformed(evt);
            }
        });

        jLabel7.setText("to");

        SaturdayComboBoxTH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01 PM", "02 PM", "03 PM", "04 PM", "05 PM", "06 PM", "07 PM", "08 PM", "09 PM", "10 PM", "11 PM", "12 AM", "01 AM", "02 AM", "03 AM", "04 AM", "05 AM", "06 AM", "07 AM", "08 AM", "09 AM", "10 AM", "11 AM", "12 PM" }));
        SaturdayComboBoxTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaturdayComboBoxTHActionPerformed(evt);
            }
        });

        SaturdayComboBoxTM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jLabel8.setText("FROM");

        SundayComboBoxFH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01 PM", "02 PM", "03 PM", "04 PM", "05 PM", "06 PM", "07 PM", "08 PM", "09 PM", "10 PM", "11 PM", "12 AM", "01 AM", "02 AM", "03 AM", "04 AM", "05 AM", "06 AM", "07 AM", "08 AM", "09 AM", "10 AM", "11 AM", "12 PM" }));
        SundayComboBoxFH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SundayComboBoxFHActionPerformed(evt);
            }
        });

        SundayComboBoxFM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        SundayComboBoxTH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01 PM", "02 PM", "03 PM", "04 PM", "05 PM", "06 PM", "07 PM", "08 PM", "09 PM", "10 PM", "11 PM", "12 AM", "01 AM", "02 AM", "03 AM", "04 AM", "05 AM", "06 AM", "07 AM", "08 AM", "09 AM", "10 AM", "11 AM", "12 PM" }));
        SundayComboBoxTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SundayComboBoxTHActionPerformed(evt);
            }
        });

        SundayComboBoxTM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jLabel9.setText("to");

        jLabel10.setText("FROM");

        MondayComboBoxFH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01 PM", "02 PM", "03 PM", "04 PM", "05 PM", "06 PM", "07 PM", "08 PM", "09 PM", "10 PM", "11 PM", "12 AM", "01 AM", "02 AM", "03 AM", "04 AM", "05 AM", "06 AM", "07 AM", "08 AM", "09 AM", "10 AM", "11 AM", "12 PM" }));
        MondayComboBoxFH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MondayComboBoxFHActionPerformed(evt);
            }
        });

        MondayComboBoxFM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        MondayComboBoxTH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01 PM", "02 PM", "03 PM", "04 PM", "05 PM", "06 PM", "07 PM", "08 PM", "09 PM", "10 PM", "11 PM", "12 AM", "01 AM", "02 AM", "03 AM", "04 AM", "05 AM", "06 AM", "07 AM", "08 AM", "09 AM", "10 AM", "11 AM", "12 PM" }));
        MondayComboBoxTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MondayComboBoxTHActionPerformed(evt);
            }
        });

        MondayComboBoxTM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jLabel11.setText("to");

        jLabel12.setText("FROM");

        TuesdayComboBoxFH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01 PM", "02 PM", "03 PM", "04 PM", "05 PM", "06 PM", "07 PM", "08 PM", "09 PM", "10 PM", "11 PM", "12 AM", "01 AM", "02 AM", "03 AM", "04 AM", "05 AM", "06 AM", "07 AM", "08 AM", "09 AM", "10 AM", "11 AM", "12 PM" }));
        TuesdayComboBoxFH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TuesdayComboBoxFHActionPerformed(evt);
            }
        });

        TuesdayComboBoxFM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        TuesdayComboBoxTH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01 PM", "02 PM", "03 PM", "04 PM", "05 PM", "06 PM", "07 PM", "08 PM", "09 PM", "10 PM", "11 PM", "12 AM", "01 AM", "02 AM", "03 AM", "04 AM", "05 AM", "06 AM", "07 AM", "08 AM", "09 AM", "10 AM", "11 AM", "12 PM" }));
        TuesdayComboBoxTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TuesdayComboBoxTHActionPerformed(evt);
            }
        });

        TuesdayComboBoxTM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jLabel13.setText("to");

        jLabel14.setText("FROM");

        WednesdayComboBoxFH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01 PM", "02 PM", "03 PM", "04 PM", "05 PM", "06 PM", "07 PM", "08 PM", "09 PM", "10 PM", "11 PM", "12 AM", "01 AM", "02 AM", "03 AM", "04 AM", "05 AM", "06 AM", "07 AM", "08 AM", "09 AM", "10 AM", "11 AM", "12 PM" }));
        WednesdayComboBoxFH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WednesdayComboBoxFHActionPerformed(evt);
            }
        });

        WednesdayComboBoxFM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        WednesdayComboBoxTH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01 PM", "02 PM", "03 PM", "04 PM", "05 PM", "06 PM", "07 PM", "08 PM", "09 PM", "10 PM", "11 PM", "12 AM", "01 AM", "02 AM", "03 AM", "04 AM", "05 AM", "06 AM", "07 AM", "08 AM", "09 AM", "10 AM", "11 AM", "12 PM" }));
        WednesdayComboBoxTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WednesdayComboBoxTHActionPerformed(evt);
            }
        });

        WednesdayComboBoxTM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jLabel15.setText("to");

        jLabel16.setText("FROM");

        ThursdayComboBoxFH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01 PM", "02 PM", "03 PM", "04 PM", "05 PM", "06 PM", "07 PM", "08 PM", "09 PM", "10 PM", "11 PM", "12 AM", "01 AM", "02 AM", "03 AM", "04 AM", "05 AM", "06 AM", "07 AM", "08 AM", "09 AM", "10 AM", "11 AM", "12 PM" }));
        ThursdayComboBoxFH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThursdayComboBoxFHActionPerformed(evt);
            }
        });

        ThursdayComboBoxFM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        ThursdayComboBoxTH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01 PM", "02 PM", "03 PM", "04 PM", "05 PM", "06 PM", "07 PM", "08 PM", "09 PM", "10 PM", "11 PM", "12 AM", "01 AM", "02 AM", "03 AM", "04 AM", "05 AM", "06 AM", "07 AM", "08 AM", "09 AM", "10 AM", "11 AM", "12 PM" }));
        ThursdayComboBoxTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThursdayComboBoxTHActionPerformed(evt);
            }
        });

        ThursdayComboBoxTM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jLabel17.setText("to");

        jLabel18.setText("FROM");

        FridayComboBoxFH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01 PM", "02 PM", "03 PM", "04 PM", "05 PM", "06 PM", "07 PM", "08 PM", "09 PM", "10 PM", "11 PM", "12 AM", "01 AM", "02 AM", "03 AM", "04 AM", "05 AM", "06 AM", "07 AM", "08 AM", "09 AM", "10 AM", "11 AM", "12 PM" }));
        FridayComboBoxFH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FridayComboBoxFHActionPerformed(evt);
            }
        });

        FridayComboBoxFM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        FridayComboBoxTH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01 PM", "02 PM", "03 PM", "04 PM", "05 PM", "06 PM", "07 PM", "08 PM", "09 PM", "10 PM", "11 PM", "12 AM", "01 AM", "02 AM", "03 AM", "04 AM", "05 AM", "06 AM", "07 AM", "08 AM", "09 AM", "10 AM", "11 AM", "12 PM" }));
        FridayComboBoxTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FridayComboBoxTHActionPerformed(evt);
            }
        });

        FridayComboBoxTM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jLabel19.setText("to");

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel20.setText("Password : ");

        jPasswordField1.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(725, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTuesday)
                                    .addComponent(jWednesday)
                                    .addComponent(jThursday)
                                    .addComponent(jFriday)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jSaturday)
                                            .addGap(70, 70, 70)
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(SaturdayComboBoxFH, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(SaturdayComboBoxFM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(SaturdayComboBoxTH, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(SaturdayComboBoxTM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jSunday)
                                                .addComponent(jMonday))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(jLabel10)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(MondayComboBoxFH, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(MondayComboBoxFM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel11)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(MondayComboBoxTH, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(MondayComboBoxTM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(jLabel8)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(SundayComboBoxFH, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(SundayComboBoxFM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel9)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(SundayComboBoxTH, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(SundayComboBoxTM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(jLabel12)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(TuesdayComboBoxFH, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(TuesdayComboBoxFM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel13)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(TuesdayComboBoxTH, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(TuesdayComboBoxTM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(jLabel14)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(WednesdayComboBoxFH, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(WednesdayComboBoxFM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel15)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(WednesdayComboBoxTH, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(WednesdayComboBoxTM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(jLabel16)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(ThursdayComboBoxFH, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(ThursdayComboBoxFM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel17)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(ThursdayComboBoxTH, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(ThursdayComboBoxTM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(jLabel18)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(FridayComboBoxFH, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(FridayComboBoxFM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel19)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(FridayComboBoxTH, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(FridayComboBoxTM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(JName, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(JEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSaturday)
                    .addComponent(jLabel6)
                    .addComponent(SaturdayComboBoxFH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaturdayComboBoxFM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(SaturdayComboBoxTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaturdayComboBoxTM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSunday)
                    .addComponent(jLabel8)
                    .addComponent(SundayComboBoxFH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SundayComboBoxFM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(SundayComboBoxTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SundayComboBoxTM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMonday)
                    .addComponent(jLabel10)
                    .addComponent(MondayComboBoxFH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MondayComboBoxFM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(MondayComboBoxTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MondayComboBoxTM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTuesday)
                    .addComponent(jLabel12)
                    .addComponent(TuesdayComboBoxFH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TuesdayComboBoxFM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(TuesdayComboBoxTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TuesdayComboBoxTM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jWednesday)
                    .addComponent(jLabel14)
                    .addComponent(WednesdayComboBoxFH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WednesdayComboBoxFM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(WednesdayComboBoxTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WednesdayComboBoxTM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jThursday)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(ThursdayComboBoxFH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ThursdayComboBoxFM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(ThursdayComboBoxTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ThursdayComboBoxTM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFriday)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(FridayComboBoxFH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FridayComboBoxFM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)
                        .addComponent(FridayComboBoxTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FridayComboBoxTM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPhoneActionPerformed

    private void JNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNameActionPerformed

    private void JEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JEmailActionPerformed

    private void jSaturdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaturdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSaturdayActionPerformed

    private void jMondayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMondayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMondayActionPerformed

    private void jTuesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTuesdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTuesdayActionPerformed

    private void SaturdayComboBoxFHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaturdayComboBoxFHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaturdayComboBoxFHActionPerformed

    private void SaturdayComboBoxTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaturdayComboBoxTHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaturdayComboBoxTHActionPerformed

    private void SundayComboBoxFHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SundayComboBoxFHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SundayComboBoxFHActionPerformed

    private void SundayComboBoxTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SundayComboBoxTHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SundayComboBoxTHActionPerformed

    private void MondayComboBoxFHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MondayComboBoxFHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MondayComboBoxFHActionPerformed

    private void MondayComboBoxTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MondayComboBoxTHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MondayComboBoxTHActionPerformed

    private void TuesdayComboBoxFHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TuesdayComboBoxFHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TuesdayComboBoxFHActionPerformed

    private void TuesdayComboBoxTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TuesdayComboBoxTHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TuesdayComboBoxTHActionPerformed

    private void WednesdayComboBoxFHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WednesdayComboBoxFHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WednesdayComboBoxFHActionPerformed

    private void WednesdayComboBoxTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WednesdayComboBoxTHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WednesdayComboBoxTHActionPerformed

    private void ThursdayComboBoxFHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThursdayComboBoxFHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThursdayComboBoxFHActionPerformed

    private void ThursdayComboBoxTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThursdayComboBoxTHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThursdayComboBoxTHActionPerformed

    private void FridayComboBoxFHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FridayComboBoxFHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FridayComboBoxFHActionPerformed

    private void FridayComboBoxTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FridayComboBoxTHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FridayComboBoxTHActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Schedule();
//        if(jSaturday.isSelected()){System.out.println("hell no Saturday "+SaturdayComboBoxFH.getItemAt(WIDTH));}
//        if(jSunday.isSelected()){System.out.println("hell no Sunday");}
//        if(jMonday.isSelected()){System.out.println("hell no Monday");}
//        if(jTuesday.isSelected()){System.out.println("hell no Tuesday");}
//        if(jWednesday.isSelected()){System.out.println("hell no Wednesday");}
//        if(jThursday.isSelected()){System.out.println("hell no Thursday");}
//        if(jFriday.isSelected()){System.out.println("yesss Friday");}
        if (validateFields()) {
            String phone = JPhone.getText();
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/maindb", "root", "");

                // إجراء فحص للتحقق مما إذا كان الاسم أو الرقم أو البريد الإلكتروني موجودين بالفعل في قاعدة البيانات
                PreparedStatement checkStmt = con.prepareStatement("SELECT * FROM Doctor WHERE DoName = ? OR DoPhone = ? OR DoEmail = ?");
                checkStmt.setString(1, JName.getText());
                checkStmt.setString(2, JPhone.getText());
                checkStmt.setString(3, JEmail.getText());
                ResultSet rs = checkStmt.executeQuery();

                if (rs.next()) {
                    // يتم عرض رسالة الخطأ إذا تم العثور على سجل بالفعل في قاعدة البيانات
                    JOptionPane.showMessageDialog(this, "Doctor name or phone or email already exists");
                } else {

                    // يتم إجراء إجراء الإدخال INSERT في قاعدة البيانات إذا لم يتم العثور على أي سجل متطابق
                    PreparedStatement insertStmt = con.prepareStatement("INSERT INTO Doctor (DoName, DoPhone, DoEmail, DoPass) VALUES (?, ?, ?, ?)");
                    String pass = new String(jPasswordField1.getPassword());
                    DOCTOR d = new DOCTOR();
                    d.setName(JName.getText());
                    d.setPhone(JPhone.getText());
                    d.setEmail(JEmail.getText());
                    d.setPass(pass);
                    insertStmt.setString(1, d.getName());
                    insertStmt.setString(2, d.getPhone());
                    insertStmt.setString(3, d.getEmail());
                    insertStmt.setString(4, d.getPass());

                    insertStmt.executeUpdate();
                    insertStmt.close();
                    dispose();
                    ADMIN_SCREEN a = new ADMIN_SCREEN();
                    a.show();
                    a.setExtendedState(MAXIMIZED_BOTH);
                    JOptionPane.showMessageDialog(this, "Successfully added");
                }

                // إغلاق الاتصال بقاعدة البيانات والكائن PreparedStatement
                checkStmt.close();
                con.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        ADMIN_SCREEN a = new ADMIN_SCREEN();
        a.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jSundayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSundayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSundayActionPerformed

    private void SaturdayComboBoxFMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaturdayComboBoxFMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaturdayComboBoxFMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADDD_SCREEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADDD_SCREEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADDD_SCREEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADDD_SCREEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADDD_SCREEN().setVisible(true);
            }
        });
    }

    private void Schedule() {
        SaturdayComboBoxFH.setSelectedItem("00");
        SaturdayComboBoxFM.setSelectedItem("00");
        SaturdayComboBoxTH.setSelectedItem("00");
        SaturdayComboBoxTM.setSelectedItem("00");
        SundayComboBoxFH.setSelectedItem("00");
        SundayComboBoxFM.setSelectedItem("00");
        SundayComboBoxTH.setSelectedItem("00");
        SundayComboBoxTM.setSelectedItem("00");
        MondayComboBoxFH.setSelectedItem("00");
        MondayComboBoxFM.setSelectedItem("00");
        MondayComboBoxTH.setSelectedItem("00");
        MondayComboBoxTM.setSelectedItem("00");
        TuesdayComboBoxFH.setSelectedItem("00");
        TuesdayComboBoxFM.setSelectedItem("00");
        TuesdayComboBoxTH.setSelectedItem("00");
        TuesdayComboBoxTM.setSelectedItem("00");
        WednesdayComboBoxFH.setSelectedItem("00");
        WednesdayComboBoxFM.setSelectedItem("00");
        WednesdayComboBoxTH.setSelectedItem("00");
        WednesdayComboBoxTM.setSelectedItem("00");
        ThursdayComboBoxFH.setSelectedItem("00");
        ThursdayComboBoxFM.setSelectedItem("00");
        ThursdayComboBoxTH.setSelectedItem("00");
        ThursdayComboBoxTM.setSelectedItem("00");
        FridayComboBoxFH.setSelectedItem("00");
        FridayComboBoxFM.setSelectedItem("00");
        FridayComboBoxTH.setSelectedItem("00");
        FridayComboBoxTM.setSelectedItem("00");
        // تعريف وإعداد المصفوفة والقائمة
        String[] WorkingHours = {};
        ArrayList<String> workingHoursList = new ArrayList<String>(Arrays.asList(WorkingHours));

// إضافة الأيام العملية وأوقات العمل للقائمة
        if (jSaturday.isSelected()) {
            workingHoursList.add("Saturday");
            workingHoursList.add(TimeConverter(SaturdayComboBoxFH.getSelectedItem().toString()) + ":" + (String) SaturdayComboBoxFM.getSelectedItem() + "-" + TimeConverter(SaturdayComboBoxTH.getSelectedItem().toString()) + ":" + (String) SaturdayComboBoxTM.getSelectedItem());
            System.out.println(TimeConverter(SaturdayComboBoxFH.getSelectedItem().toString()) + ":" + (String) SaturdayComboBoxFM.getSelectedItem() + "-" + TimeConverter(SaturdayComboBoxTH.getSelectedItem().toString()) + ":" + (String) SaturdayComboBoxTM.getSelectedItem());
        }
        if (jSunday.isSelected()) {
            workingHoursList.add("Sunday");
            workingHoursList.add(TimeConverter(SundayComboBoxFH.getSelectedItem().toString()) + ":" + (String) SundayComboBoxFM.getSelectedItem() + "-" + TimeConverter(SundayComboBoxTH.getSelectedItem().toString()) + ":" + (String) SundayComboBoxTM.getSelectedItem());
        }
        if (jMonday.isSelected()) {
            workingHoursList.add("Saturday");
            workingHoursList.add(TimeConverter(MondayComboBoxFH.getSelectedItem().toString()) + ":" + (String) MondayComboBoxFM.getSelectedItem() + "-" + TimeConverter(MondayComboBoxTH.getSelectedItem().toString()) + ":" + (String) MondayComboBoxTM.getSelectedItem());
        }
        if (jTuesday.isSelected()) {
            workingHoursList.add("Saturday");
            workingHoursList.add(TimeConverter(TuesdayComboBoxFH.getSelectedItem().toString()) + ":" + (String) TuesdayComboBoxFM.getSelectedItem() + "-" + TimeConverter(TuesdayComboBoxTH.getSelectedItem().toString()) + ":" + (String) TuesdayComboBoxTM.getSelectedItem());

        }
        if (jWednesday.isSelected()) {
            workingHoursList.add("Wednesday");
            workingHoursList.add(TimeConverter(WednesdayComboBoxFH.getSelectedItem().toString()) + ":" + (String) WednesdayComboBoxFM.getSelectedItem() + "-" + TimeConverter(WednesdayComboBoxTH.getSelectedItem().toString()) + ":" + (String) WednesdayComboBoxTM.getSelectedItem());
        }
        if (jThursday.isSelected()) {
            workingHoursList.add("Thursday");
            workingHoursList.add(TimeConverter(ThursdayComboBoxFH.getSelectedItem().toString()) + ":" + (String) ThursdayComboBoxFM.getSelectedItem() + "-" + TimeConverter(ThursdayComboBoxTH.getSelectedItem().toString()) + ":" + (String) ThursdayComboBoxTM.getSelectedItem());
        }
        if (jFriday.isSelected()) {
            workingHoursList.add("Friday");
            workingHoursList.add(TimeConverter(FridayComboBoxFH.getSelectedItem().toString()) + ":" + (String) FridayComboBoxFM.getSelectedItem() + "-" + TimeConverter(FridayComboBoxTH.getSelectedItem().toString()) + ":" + (String) FridayComboBoxTM.getSelectedItem());
        }
        String[] WorkingHours3 = workingHoursList.toArray(new String[workingHoursList.size()]);

// استرداد مواعيد الأيام وطباعتها بالتنسيق المطلوب
        DSCHEDULE scheduleE = new DSCHEDULE(WorkingHours3);
        List<String[]> appointments = scheduleE.getAppointments();
        if (appointments.isEmpty()) {
            System.out.println("No appointments available");
        } else {

            for (String[] dayAndAppointments : appointments) {
                System.out.print(dayAndAppointments[0]);
                for (int i = 1; i < dayAndAppointments.length; i++) {
                    System.out.print(" " + dayAndAppointments[i]);
                }
                System.out.println();
            }

        }
    }
    /////////////////////
    ////////////////////////////////////////////////////////////////////////////////////التحويل لنظام 24 ساعة/////////////////////////////////////////////////////////////////////

    private String TimeConverter(String H12) {
        String timeString = H12;
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("hh a", Locale.ENGLISH);
        LocalTime time = LocalTime.parse(timeString, formatter);
        String time24hr = time.format(DateTimeFormatter.ofPattern("HH"));
        System.out.println(time24hr);
        return time24hr;

    }

    ////////////////////////////////////////////////////////////////////////////////////التأكد من المعلومات/////////////////////////////////////////////////////////////////////
    private boolean validateFields() {
        // فحص ما إذا كانت جميع الحقول مملوءة بشكل صحيح

        if (JName.getText().isEmpty() || JPhone.getText().isEmpty() || JEmail.getText().isEmpty() || jPasswordField1.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Please fill all required fields");
            return false;
        }
        // فحص ما إذا كان رقم الهاتف يبدأ بـ 0 ويحتوي على 10 أو 14 رقمًا
        String phoneRegex = "^0[0-9]{9,12}$";
        if (!JPhone.getText().matches(phoneRegex)) {
            JOptionPane.showMessageDialog(this, "Please enter a valid phone number starting with 0 or +966 and consisting of 10 or 14 digits");
            return false;
        }
        // فحص ما إذا كانت البريد الإلكتروني صالحة
        String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
        if (!JEmail.getText().matches(emailRegex)) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address");
            return false;
        }
        // فحص ما إذا كانت كلمة المرور قد تم إدخالها
        if (new String(jPasswordField1.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a password");
            return false;
        }
        return true;
    }
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> FridayComboBoxFH;
    private javax.swing.JComboBox<String> FridayComboBoxFM;
    private javax.swing.JComboBox<String> FridayComboBoxTH;
    private javax.swing.JComboBox<String> FridayComboBoxTM;
    private javax.swing.JTextField JEmail;
    private javax.swing.JTextField JName;
    private javax.swing.JTextField JPhone;
    private javax.swing.JComboBox<String> MondayComboBoxFH;
    private javax.swing.JComboBox<String> MondayComboBoxFM;
    private javax.swing.JComboBox<String> MondayComboBoxTH;
    private javax.swing.JComboBox<String> MondayComboBoxTM;
    private javax.swing.JComboBox<String> SaturdayComboBoxFH;
    private javax.swing.JComboBox<String> SaturdayComboBoxFM;
    private javax.swing.JComboBox<String> SaturdayComboBoxTH;
    private javax.swing.JComboBox<String> SaturdayComboBoxTM;
    private javax.swing.JComboBox<String> SundayComboBoxFH;
    private javax.swing.JComboBox<String> SundayComboBoxFM;
    private javax.swing.JComboBox<String> SundayComboBoxTH;
    private javax.swing.JComboBox<String> SundayComboBoxTM;
    private javax.swing.JComboBox<String> ThursdayComboBoxFH;
    private javax.swing.JComboBox<String> ThursdayComboBoxFM;
    private javax.swing.JComboBox<String> ThursdayComboBoxTH;
    private javax.swing.JComboBox<String> ThursdayComboBoxTM;
    private javax.swing.JComboBox<String> TuesdayComboBoxFH;
    private javax.swing.JComboBox<String> TuesdayComboBoxFM;
    private javax.swing.JComboBox<String> TuesdayComboBoxTH;
    private javax.swing.JComboBox<String> TuesdayComboBoxTM;
    private javax.swing.JComboBox<String> WednesdayComboBoxFH;
    private javax.swing.JComboBox<String> WednesdayComboBoxFM;
    private javax.swing.JComboBox<String> WednesdayComboBoxTH;
    private javax.swing.JComboBox<String> WednesdayComboBoxTM;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JRadioButton jFriday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jMonday;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jSaturday;
    private javax.swing.JRadioButton jSunday;
    private javax.swing.JRadioButton jThursday;
    private javax.swing.JRadioButton jTuesday;
    private javax.swing.JRadioButton jWednesday;
    // End of variables declaration//GEN-END:variables
}
